name = "ojcard"
main = "worker.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "ojappcard"
database_id = "6794f958-c419-4488-b17c-b596a3e7274f"

[[r2_buckets]]
binding = "R2"
bucket_name = "ojapp-card"


[[routes]]
pattern = "https://ojapp.app/card/api/*"
zone_id = "1aa9f4c82250c7dffedb68a5bea7e2b5"

[[routes]]
pattern = "https://ojapp.app/card/@*"
zone_id = "1aa9f4c82250c7dffedb68a5bea7e2b5"

